//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.30 at 04:43:01 PM IST 
//


package com.bank.banking;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bank.banking package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateAccountRequest_QNAME = new QName("http://bank.com/banking", "createAccountRequest");
    private final static QName _CreateAccountResponse_QNAME = new QName("http://bank.com/banking", "createAccountResponse");
    private final static QName _GetAccountRequest_QNAME = new QName("http://bank.com/banking", "getAccountRequest");
    private final static QName _GetAccountResponse_QNAME = new QName("http://bank.com/banking", "getAccountResponse");
    private final static QName _DepositRequest_QNAME = new QName("http://bank.com/banking", "depositRequest");
    private final static QName _DepositResponse_QNAME = new QName("http://bank.com/banking", "depositResponse");
    private final static QName _WithdrawRequest_QNAME = new QName("http://bank.com/banking", "withdrawRequest");
    private final static QName _WithdrawResponse_QNAME = new QName("http://bank.com/banking", "withdrawResponse");
    private final static QName _TransferRequest_QNAME = new QName("http://bank.com/banking", "transferRequest");
    private final static QName _TransferResponse_QNAME = new QName("http://bank.com/banking", "transferResponse");
    private final static QName _GetTransactionHistoryRequest_QNAME = new QName("http://bank.com/banking", "getTransactionHistoryRequest");
    private final static QName _GetTransactionHistoryResponse_QNAME = new QName("http://bank.com/banking", "getTransactionHistoryResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bank.banking
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateAccountRequest }
     * 
     */
    public CreateAccountRequest createCreateAccountRequest() {
        return new CreateAccountRequest();
    }

    /**
     * Create an instance of {@link CreateAccountResponse }
     * 
     */
    public CreateAccountResponse createCreateAccountResponse() {
        return new CreateAccountResponse();
    }

    /**
     * Create an instance of {@link GetAccountRequest }
     * 
     */
    public GetAccountRequest createGetAccountRequest() {
        return new GetAccountRequest();
    }

    /**
     * Create an instance of {@link GetAccountResponse }
     * 
     */
    public GetAccountResponse createGetAccountResponse() {
        return new GetAccountResponse();
    }

    /**
     * Create an instance of {@link DepositRequest }
     * 
     */
    public DepositRequest createDepositRequest() {
        return new DepositRequest();
    }

    /**
     * Create an instance of {@link DepositResponse }
     * 
     */
    public DepositResponse createDepositResponse() {
        return new DepositResponse();
    }

    /**
     * Create an instance of {@link WithdrawRequest }
     * 
     */
    public WithdrawRequest createWithdrawRequest() {
        return new WithdrawRequest();
    }

    /**
     * Create an instance of {@link WithdrawResponse }
     * 
     */
    public WithdrawResponse createWithdrawResponse() {
        return new WithdrawResponse();
    }

    /**
     * Create an instance of {@link TransferRequest }
     * 
     */
    public TransferRequest createTransferRequest() {
        return new TransferRequest();
    }

    /**
     * Create an instance of {@link TransferResponse }
     * 
     */
    public TransferResponse createTransferResponse() {
        return new TransferResponse();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryRequest }
     * 
     */
    public GetTransactionHistoryRequest createGetTransactionHistoryRequest() {
        return new GetTransactionHistoryRequest();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryResponse }
     * 
     */
    public GetTransactionHistoryResponse createGetTransactionHistoryResponse() {
        return new GetTransactionHistoryResponse();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccountRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateAccountRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://bank.com/banking", name = "createAccountRequest")
    public JAXBElement<CreateAccountRequest> createCreateAccountRequest(CreateAccountRequest value) {
        return new JAXBElement<CreateAccountRequest>(_CreateAccountRequest_QNAME, CreateAccountRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccountResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateAccountResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://bank.com/banking", name = "createAccountResponse")
    public JAXBElement<CreateAccountResponse> createCreateAccountResponse(CreateAccountResponse value) {
        return new JAXBElement<CreateAccountResponse>(_CreateAccountResponse_QNAME, CreateAccountResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccountRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAccountRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://bank.com/banking", name = "getAccountRequest")
    public JAXBElement<GetAccountRequest> createGetAccountRequest(GetAccountRequest value) {
        return new JAXBElement<GetAccountRequest>(_GetAccountRequest_QNAME, GetAccountRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccountResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAccountResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://bank.com/banking", name = "getAccountResponse")
    public JAXBElement<GetAccountResponse> createGetAccountResponse(GetAccountResponse value) {
        return new JAXBElement<GetAccountResponse>(_GetAccountResponse_QNAME, GetAccountResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DepositRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DepositRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://bank.com/banking", name = "depositRequest")
    public JAXBElement<DepositRequest> createDepositRequest(DepositRequest value) {
        return new JAXBElement<DepositRequest>(_DepositRequest_QNAME, DepositRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DepositResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DepositResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://bank.com/banking", name = "depositResponse")
    public JAXBElement<DepositResponse> createDepositResponse(DepositResponse value) {
        return new JAXBElement<DepositResponse>(_DepositResponse_QNAME, DepositResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WithdrawRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WithdrawRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://bank.com/banking", name = "withdrawRequest")
    public JAXBElement<WithdrawRequest> createWithdrawRequest(WithdrawRequest value) {
        return new JAXBElement<WithdrawRequest>(_WithdrawRequest_QNAME, WithdrawRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WithdrawResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WithdrawResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://bank.com/banking", name = "withdrawResponse")
    public JAXBElement<WithdrawResponse> createWithdrawResponse(WithdrawResponse value) {
        return new JAXBElement<WithdrawResponse>(_WithdrawResponse_QNAME, WithdrawResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransferRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransferRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://bank.com/banking", name = "transferRequest")
    public JAXBElement<TransferRequest> createTransferRequest(TransferRequest value) {
        return new JAXBElement<TransferRequest>(_TransferRequest_QNAME, TransferRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransferResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransferResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://bank.com/banking", name = "transferResponse")
    public JAXBElement<TransferResponse> createTransferResponse(TransferResponse value) {
        return new JAXBElement<TransferResponse>(_TransferResponse_QNAME, TransferResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransactionHistoryRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetTransactionHistoryRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://bank.com/banking", name = "getTransactionHistoryRequest")
    public JAXBElement<GetTransactionHistoryRequest> createGetTransactionHistoryRequest(GetTransactionHistoryRequest value) {
        return new JAXBElement<GetTransactionHistoryRequest>(_GetTransactionHistoryRequest_QNAME, GetTransactionHistoryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransactionHistoryResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetTransactionHistoryResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://bank.com/banking", name = "getTransactionHistoryResponse")
    public JAXBElement<GetTransactionHistoryResponse> createGetTransactionHistoryResponse(GetTransactionHistoryResponse value) {
        return new JAXBElement<GetTransactionHistoryResponse>(_GetTransactionHistoryResponse_QNAME, GetTransactionHistoryResponse.class, null, value);
    }

}
