//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.30 at 04:43:01 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bank.com/banking", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bank.banking;
