//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.30 at 04:43:01 PM IST 
//


package com.bank.banking;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransferResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransferResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fromTransaction" type="{http://bank.com/banking}Transaction"/&gt;
 *         &lt;element name="toTransaction" type="{http://bank.com/banking}Transaction"/&gt;
 *         &lt;element name="fromAccountBalance" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="toAccountBalance" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransferResponse", propOrder = {
    "fromTransaction",
    "toTransaction",
    "fromAccountBalance",
    "toAccountBalance",
    "message"
})
public class TransferResponse {

    @XmlElement(required = true)
    protected Transaction fromTransaction;
    @XmlElement(required = true)
    protected Transaction toTransaction;
    @XmlElement(required = true)
    protected BigDecimal fromAccountBalance;
    @XmlElement(required = true)
    protected BigDecimal toAccountBalance;
    @XmlElement(required = true)
    protected String message;

    /**
     * Gets the value of the fromTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link Transaction }
     *     
     */
    public Transaction getFromTransaction() {
        return fromTransaction;
    }

    /**
     * Sets the value of the fromTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transaction }
     *     
     */
    public void setFromTransaction(Transaction value) {
        this.fromTransaction = value;
    }

    /**
     * Gets the value of the toTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link Transaction }
     *     
     */
    public Transaction getToTransaction() {
        return toTransaction;
    }

    /**
     * Sets the value of the toTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transaction }
     *     
     */
    public void setToTransaction(Transaction value) {
        this.toTransaction = value;
    }

    /**
     * Gets the value of the fromAccountBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFromAccountBalance() {
        return fromAccountBalance;
    }

    /**
     * Sets the value of the fromAccountBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFromAccountBalance(BigDecimal value) {
        this.fromAccountBalance = value;
    }

    /**
     * Gets the value of the toAccountBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getToAccountBalance() {
        return toAccountBalance;
    }

    /**
     * Sets the value of the toAccountBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setToAccountBalance(BigDecimal value) {
        this.toAccountBalance = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

}
